import React from 'react';

export default function ServiceTermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-center mb-8">User Agreement</h1>
      
      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <p className="mb-4">
          Please read this User Agreement ("Agreement") carefully before using the Pupu AI application ("App") and related services (collectively referred to as the "Services"). By accessing or using the Services, you agree to be bound by this Agreement. If you do not agree to all the terms and conditions of this Agreement, please do not use the Services. 
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">1. Definitions</h2>
        <ul className="list-disc pl-6">
          <li className="mb-2">
            <span className="font-medium">"Pupu AI" or "we," "us," "our"</span> refers to the entity that operates the Services.
          </li>
          <li className="mb-2">
            <span className="font-medium">"User" or "you," "your"</span> refers to any individual or entity who accesses or uses the Services.
          </li>
          <li>
            <span className="font-medium">"Content"</span> includes all text, audio, images, stories, and other materials generated, uploaded, or provided through the Services, including but not limited to the stories generated by the AI.
          </li>
        </ul>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">2. Description of Services</h2>
        <p className="mb-4">
          Pupu AI is an application designed to allow parents to interact with AI to customize and generate engaging stories. Through the App, users can communicate with the AI to define storylines, and the AI will generate corresponding stories, which the App will then play back to users. We reserve the right to modify, suspend, or discontinue the Services (or any part thereof) at any time, with or without notice.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">3. User Eligibility</h2>
        <p className="mb-4">
          You must be of legal age in your jurisdiction to use the services. If you are under the legal age, you must have the consent of your parent or legal guardian to use the Services. You represent and warrant that you have the legal right and ability to enter into this Agreement and comply with all of its terms.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">4. User Responsibilities</h2>
        <div className="ml-4">
          <h3 className="text-xl font-medium mb-2">4.1 Account Security</h3>
          <p className="mb-4">
            You are responsible for maintaining the confidentiality of your account information, including your password. You are fully responsible for all activities that occur under your account. If you become aware of any unauthorized use of your account, you must notify us immediately.
          </p>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
        <div className="ml-4">
          <h3 className="text-xl font-medium mb-2">5.1 Ownership</h3>
          <p className="mb-4">
            All intellectual property rights in and to the Services, including but not limited to the App, software code, trademarks, logos, and user interfaces, are owned by us or our licensors. You are granted a limited, non-exclusive, non-transferable license to use the Services solely for your personal, non-commercial use in accordance with this Agreement.
          </p>

          <h3 className="text-xl font-medium mb-2">5.2 User-Generated Content</h3>
          <p className="mb-4">
            You retain all ownership rights in the Content you submit or generate through the Services. By submitting or generating Content through the Services, you grant us a worldwide, royalty-free, sub-licensable, transferable license to use, reproduce, distribute, display, and perform the Content in connection with the operation of the Services.
          </p>

          <h3 className="text-xl font-medium mb-2">5.3 AI-Generated Content</h3>
          <p>
            The AI-generated stories are considered a joint work of you and us. You and we share the copyright in the AI-generated Content, and you agree that we may use, reproduce, distribute, display, and perform the AI-generated Content for the purposes of providing and promoting the Services.
          </p>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">13. Privacy Policy</h2>
        <p className="mb-4">
          Your use of the Services is also subject to our Privacy Policy, which describes how we collect, use, store, and disclose your personal information. Please review our Privacy Policy carefully. By using the Services, you consent to the collection, use, and disclosure of your personal information as described in the Privacy Policy.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">14. Termination</h2>
        <p className="mb-4">
          We may terminate or suspend your access to the Services at any time, without prior notice, if we determine, in our sole discretion, that you have violated this Agreement or any applicable laws. Upon termination or suspension, your right to use the Services immediately ceases, and you are responsible for deleting any Content you have stored on the Services.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">15. Limitation of Liability</h2>
        <p className="mb-4">
          To the maximum extent permitted by law, in no event shall we be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Services, including but not limited to damages for loss of profits, data, or other intangible losses, even if we have been advised of the possibility of such damages.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">16. Indemnification</h2>
        <p className="mb-4">
          You agree to indemnify and hold us, our officers, directors, employees, agents, and licensors harmless from and against any and all claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in connection with your use of the Services, your violation of this Agreement, or your infringement of any third-party rights.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">17. Governing Law and Jurisdiction</h2>
        <p className="mb-4">
          This Agreement shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising out of or in connection with this Agreement shall be subject to the exclusive jurisdiction of the courts of [Jurisdiction].
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-2xl font-semibold mb-4">18. Amendments</h2>
        <p className="mb-4">
          We reserve the right to modify this Agreement at any time. We will notify you of any material changes by posting the revised Agreement on the App or sending you a notification. Your continued use of the Services after the effective date of the revised Agreement constitutes your acceptance of the changes.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-semibold mb-4">19. Entire Agreement</h2>
        <p className="mb-4">
          This Agreement constitutes the entire agreement between you and us regarding your use of the Services and supersedes all prior agreements and understandings, oral or written, relating to the same subject matter.
        </p>
        <p>
          If you have any questions or concerns about this Agreement or the Services, please contact us at support@pupupuai.com
        </p>
      </div>
    </div>
  )
}
